theme: jekyll-theme-minimal
title: Modélisation Collaborative
description: Agir pour comprendre. Comprendre pour agir.
#logo: [Location of the logo]
#google_analytics: [Your Google Analytics tracking ID]
